"""empty message

Revision ID: b5c23f2dff4a
Revises: b6f1b31362ad
Create Date: 2021-07-20 19:20:19.848236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c23f2dff4a'
down_revision = 'b6f1b31362ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('computername', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'computername')
    # ### end Alembic commands ###
