"""empty message

Revision ID: b6f1b31362ad
Revises: daf3a4286e21
Create Date: 2021-06-30 17:54:42.433335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f1b31362ad'
down_revision = 'daf3a4286e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('computername', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host', 'computername')
    # ### end Alembic commands ###
