"""adds file_input field in task table

Revision ID: cf73878ec3b9
Revises: 33251f3d526e
Create Date: 2021-08-08 20:28:45.013953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf73878ec3b9'
down_revision = '33251f3d526e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('file_input', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'file_input')
    # ### end Alembic commands ###
